spring:
  config:
    import:
      - app.yml
      - aws.yml
      - oauth2.yml

  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true

    show-sql: true

  data:
    redis:
      host: localhost
      port: 6379

cloud:
  aws:
    region:
      static: ap-northeast-2
    stack:
      auto: false
