spring:
  config:
    import:
      - aws.yml
      - oauth2.yml

  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB
  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        format_sql: true

    show-sql: true

cloud:
  aws:
    region:
      static: ap-northeast-2
    stack:
      auto: false

