spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/taekgwan
    username: root
    password: WjdWodnr#&33

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 691365998287-7gasio9ao7ld61j1tp21r8ku8dtacl86.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

          kakao:
            client-id: 0d75e1511a90bfb55ff4c8e07287a72e
            client-secret: DvIm7fL0iW9yuUIoiMPdaJaXpmqVSzWd
            scope:
              - profile_nickname
              - account_email
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-authentication-method: client_secret_post

          naver:
            client-id: sVQjKP2Z0qfauDRLe2ye
            client-secret: 2wEnXf7BGG
            scope:
              - name
              - email
              - nickname
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true

    show-sql: true

